version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01

    working_directory: ~/

    steps:
      - setup_remote_docker:

        

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/






                      - restore_cache:
            keys:
              - v1-{{ .Branch }}
            paths:
              - /caches/app.tar
        - run:
            name: Build Docker image
            command: docker build --cache-from=app -t helsingborgstad/labs-api-notification:$CIRCLE_SHA1 .
        - run:
            name: Save Docker image layer cache
            command: |
              mkdir -p /caches
              docker save -o /caches/app.tar app
        - save_cache:
            key: v1-{{ .Branch }}-{{ epoch }}
            paths:
              - /caches/app.tar