# Helsingborg Stad CircleCI Build Config
#
# Supported Build process: Dockerized NodeJS Apps deployed on Heroku
#
# -- TESTS -- 
#
# This build config will make a basic warmup of the docker. It's up 
# to the application itself to run the required tests to validate 
# the functionality. This build will fail if any error message is thrown.
#
# -- REQUIRED ENVIROMENT VARIABLES -- 
#
# DOCKERHUB_LOGIN       Username on dockerhub [Found in confluence]
# DOCKERHUB_PASSWORD    Password on dockerhub [Found in confluence]
# 
# HEROKU_API_KEY        General API code [Generated in Heroku admin]
# HEROKU_APP_NAME       The name of the application in Heroku
#
# IMAGE_NAME            The name of the image on docker hub, circleci and github. 
#
# -- AUTHORS -- 
#
# Sebastian Thulin (sebastian.thulin@helsingborg.se)
#
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  runapp:
    executor: heroku/default
    steps:
      - heroku/install
      - run:
        name: Trigger application on heroku
        command: | 
          heroku container:release web

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag $IMAGE_NAME registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            
  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: feature/deploy
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: feature/deploy
      - runapp:
          requires:
            - publish-latest
          filters:
            branches:
              only: feature/deploy
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/