version: 2.0
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker:
          version: 17.03.0-ce
      - run:
          name: Build Docker image from repository at git url https://github.com/helsingborg-stad/labs-api-notification.git#container:feature/deploy
          command: docker build https://github.com/helsingborg-stad/labs-api-notification.git#container:feature/deploy
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push helsingborgstad/labs-api-notification:$CIRCLE_SHA1
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag helsingborgstad/labs-api-notification:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web